# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en"
  contentDir = "content/en"

# Configure the Spanish version of the site.
[es]
  languageCode = "es"
  contentDir = "content/es"

# Configure the Basque version of the site.
[eu]
  languageCode = "eu"
  contentDir = "content/eu"

# Uncomment the lines below to configure your website in a second language.
#[zh]
#  languageCode = "zh-Hans"
#  contentDir = "content/zh"
#  title = "Chinese website title..."
#  [zh.params]
#    description = "Site description in Chinese..."
#  [[zh.menu.main]]
#    name = "Wo"
#    url = "#about"
#    weight = 1
