# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

theme: minimal
day_night: true
font: ''
font_size: L

# SEO
site_type: Person
local_business_type: ''
org_name: ''
description: >-
  Informatika Ingeniaritzako Graduko ikaslea Euskal Herriko Unibertsitatean
  (UPV/EHU)
twitter: juletxara

# Contact (edit or remove options as required)

email: juletxara@gmail.com
# phone: 888 888 88 88
address:
  street: 'Informatika Fakultatea<br> Manuel Lardizabal Ibilbidea, 1'
  city: Donostia
  region: Gipuzkoa
  postcode: '20018'
  country: Espainia
  country_code: ES
# coordinates:
#   latitude: '43.307205'
#   longitude: '-2.010843'
# directions: Enter Building 1 and take the stairs to Office 200 on Floor 2
# office_hours:
#   - 'Monday 10:00 to 13:00'
#   - 'Wednesday 09:00 to 10:00'
# appointment_url: 'https://calendly.com'
contact_links:
  - icon: github
    icon_pack: fab
    name: juletx
    link: 'https://github.com/juletx'
  - icon: linkedin
    icon_pack: fab
    name: juletxara
    link: 'https://www.linkedin.com/in/juletxara'
  - icon: twitter
    icon_pack: fab
    name: juletxara
    link: 'https://twitter.com/juletxara'
  - icon: instagram
    icon_pack: fab
    name: juletxara
    link: 'https://www.instagram.com/juletxara'

# Site header

main_menu:
  enable: true
  align: l
  show_logo: true
  show_language: false
  show_day_night: true
  show_search: true
  show_translations: true
  highlight_active_link: true

# Site footer

footer:
  show_translations: true

# Localization

date_format: 'Jan 2, 2006'
time_format: '15:04'
address_format: en-us

# Site features

highlight: true
highlight_languages:
  - python
math: false
diagram: false
privacy_pack: true
edit_page:
  repo_url: 'https://github.com/juletx/academic-website'
  content_dir: ''
  repo_branch: master
  editable:
    page: false
    post: false
    book: true
show_related:
  book: true
  page: false
  post: true
  project: true
  publication: true
  event: true
reading_time: true
section_pager: false
docs_section_pager: true
sharing: true
copyright_license:
  enable: true
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'
highlight_superuser: true
link_authors: true
abstract_length: 135
plugins_js: []
avatar:
  gravatar: true
  shape: circle
publications:
  date_format: January 2006
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  event_view: 2
breadcrumb:
  page_types:
    book: true
comments:
  provider: disqus
  commentable:
    page: true
    post: true
    book: true
    project: true
    publication: true
    event: true
  disqus:
    shortname: julenetxaniz
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  provider: ''
  api_key: ''
  zoom: 16
marketing:
  google_analytics: ''
  google_tag_manager: GTM-NP9JZHR
  google_site_verification: ''
  baidu_site_verification: ''
  baidu_tongji: ''
cms:
  branch: master
  local_backend: true
icon:
  pack:
    ai: true
